language: c
sudo: true
script:
  - export REPO_ROOT="/home/travis/build/AwesDea/osp3"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt update
  - sudo apt-get install linux-headers-$(uname -r)
  - sudo apt-get install build-essential fakeroot
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - cd $REPO_ROOT/
  - pwd
  - ls
  - patch -p1 < FIFO.patch || exit
  - sudo make clean
  - fakeroot make -j $(nproc) deb-pkg
  - cd ..
  - ls
  - ls -la
after_success:
  - echo success
